version: '3.8'

services:
  aicovergen:
    build: .
    container_name: aicovergen-api
    ports:
      - "8000:8000"
    volumes:
      - ./rvc_models:/app/rvc_models
      - ./uvr_models:/app/uvr_models
      - ./song_output:/app/song_output
      - ./temp:/app/temp
    environment:
      - PYTHONPATH=/app/src
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    container_name: aicovergen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 